# Generated by Django 5.1.7 on 2025-03-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('lecturer', 'lecturer'), ('staff', 'staff'), ('student', 'student')], max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
