# Generated by Django 5.1.7 on 2025-03-26 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_compliment_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'academic'), ('finance', 'finance'), ('hostel', 'hostel'), ('library', 'library'), ('medical', 'medical'), ('security', 'security'), ('transport', 'transport'), ('complaint', 'complaint')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('on-progress', 'on-progress'), ('resolved', 'resolved')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_compliment_app.users')),
            ],
        ),
    ]
