# Generated by Django 5.1.7 on 2025-03-26 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_compliment_app', '0002_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_compliment_app.users')),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain_compliment_app.feedbacks')),
            ],
        ),
    ]
