# Generated by Django 5.1.7 on 2025-03-26 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_compliment_app', '0003_adminresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=100)),
                ('total_complaints', models.IntegerField()),
                ('total_compliments', models.IntegerField()),
                ('total_feedbacks', models.IntegerField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='title',
            field=models.CharField(choices=[('complain', 'complain'), ('compliment', 'compliment')], default='complain', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complain_compliment_app.users'),
        ),
    ]
