# Generated by Django 5.1.7 on 2025-03-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_compliment_app', '0005_adminresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='email_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
