# Generated by Django 5.1.7 on 2025-03-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_compliment_app', '0006_feedbacks_email_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='total_resolved',
            field=models.IntegerField(default=0),
        ),
    ]
