# Generated by Django 5.1.7 on 2025-04-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_compliment_app', '0007_report_total_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(blank=True, choices=[('academic', 'academic'), ('health and wellness', 'health and wellness'), ('administration and support', 'administration and support'), ('ict and communication', 'ict and communication'), ('student services', 'student services'), ('maintenance and environment', 'maintenance and environment')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='category',
            field=models.CharField(choices=[('academic', 'academic'), ('health and wellness', 'health and wellness'), ('administration and support', 'administration and support'), ('ict and communication', 'ict and communication'), ('student services', 'student services'), ('maintenance and environment', 'maintenance and environment')], max_length=100),
        ),
    ]
